-- CreateEnum
CREATE TYPE "AdArea" AS ENUM ('COVER_PAGE', 'INTERIOR_LEFT', 'INTERIOR_RIGHT', 'CLASSIFIED_SECTION', 'BACK_COVER');

-- AlterTable
ALTER TABLE "ad_units" ADD COLUMN     "area" "AdArea" NOT NULL DEFAULT 'COVER_PAGE';
